### ISSUE TITLE
Create new subscriber error : "Cannot read property '_value' of undefined"

### ISSUE THREAD

**Issue by ramukima** [corenova/yang-cord#3]
bash-4.3$ curl -X POST localhost:5050/cord:subscriber -H 'content-type: application/json' -d '{ "id": 12, "service-specific-id": 2020, "demo": true }'
{
  "error": {
    "message": "Cannot read property '_value' of undefined"
  }
}bash-4.3$

**Comment by sekur** [comment]
Thanks for flagging, I'll be addressing this during the `yang-express` update today.
